### ISSUE TITLE
UnrecognizedPropertyException: Unrecognized field "signatures"

### ISSUE THREAD

**Issue by chinaryov** [ic4j/ic4j-agent#6]
Hello!

I hope this message finds you well. I am writing to report an issue with query requests that have recently started failing with an error. Interestingly, when making an update call, everything works as expected. This problem appears to be isolated to specific canisters, and it's possible that there has been a change in the protocol.

Below is a simplified code snippet demonstrating the issue with the query method on a canister, where the requests are failing:
```
    public static void main(String[] args) throws URISyntaxException, ExecutionException, InterruptedException {
        final Identity anonymousIdentity = new AnonymousIdentity();
        final ReplicaTransport replicaTransport = ReplicaApacheHttpTransport.create("https://ic0.app");
        final Agent agent = new AgentBuilder().transport(replicaTransport).identity(anonymousIdentity).build();

        final IDLArgs idlArgs = IDLArgs.create(Collections.emptyList());
        final byte[] argsBytes = idlArgs.toBytes();

        final Principal canisterId = Principal.fromString("zu4fl-riaaa-aaaak-ae6eq-cai");
        final CompletableFuture<byte[]> completableFuture = agent.queryRaw(canisterId,
                canisterId, "stats", argsBytes, Optional.empty());

        final byte[] output = completableFuture.get();
        System.out.println("output.length = " + output.length);
    }
```

Exception:
```
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "signatures" (class org.ic4j.agent.replicaapi.QueryResponse), not marked as ignorable (8 known properties: "status", "error_code", "headers", "reject_message", "replied", "reply", "reject_code", "rejected"])
 at [Source: (byte[])[257 bytes]; byte offset: #120] (through reference chain: org.ic4j.agent.replicaapi.QueryResponse["signatures"])
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "signatures" (class org.ic4j.agent.replicaapi.QueryResponse), not marked as ignorable (8 known properties: "status", "error_code", "headers", "reject_message", "replied", "reply", "reject_code", "rejected"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1132)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2202)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1705)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1683)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:320)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3738)
	at org.ic4j.agent.Agent.lambda$queryEndpoint$3(Agent.java:373)
	... 29 more
```

I would appreciate your assistance in investigating and resolving this issue. If you require any additional information to help diagnose the problem, please let me know, and I will provide them promptly.

Thank you for your attention to this matter.

Sincerely,
Alexander

**Comment by rdobrik** [comment]
Hi Alexander,

Thanks for reporting this issue. Let me check, if Dfinity added signatures property to QueryResponse message. They made some changes lately to Status response. 

Roman

**Comment by rdobrik** [comment]
yeah there is a new property signatures in query response. https://forum.dfinity.org/t/feature-discussion-replica-signed-queries/21793/5

I can add this field to our Java class. Make it optional .

**Comment by rdobrik** [comment]
Fixed the problem in 0.6.19.6 Agent patch release. If you need just patch it with fixed class here is updated code https://github.com/ic4j/ic4j-agent/blob/master/src/main/java/org/ic4j/agent/replicaapi/QueryResponse.java

From now on I added ignore unknown flag set to true, so in the future any new property will not break the code.

**Comment by chinaryov** [comment]
Big thanks for the speedy fix! Your help is much appreciated. I've tested new version, and it works perfectly now.

**Comment by rdobrik** [comment]
Alexander, this was a very good catch. Looks like they introduced it just lately, I was testing it a few weeks ago it was working fine. Now I am ignoring unknown properties in all messages from ICP.
